---
server_ip: "163.192.117.50"
admin_user: sysadmin
backup_dir: "/var/backups/webserver01"
backup_retention_days: 7

fail2ban_maxretry: 5
fail2ban_bantime: 3600
fail2ban_findtime: 600
fail2ban_ignoreip:
  - "172.59.190.159"
  - "208.59.56.247"
